USE ProjectHub;
GO

-- Default settings (theme colors, university branding)
MERGE dbo.Settings AS t
USING (VALUES
    ('theme_primary', '#16A34A'),
    ('theme_secondary', '#2563EB'),
    ('theme_accent', '#38BDF8'),
    ('university_name', 'Harvard University'),
    ('university_short', 'HU'),
    ('logo_path', '/university-logo.png'),
    ('ai_similarity_threshold', '60')
) AS s (SettingKey, SettingValue)
ON t.SettingKey = s.SettingKey
WHEN NOT MATCHED THEN INSERT (SettingKey, SettingValue) VALUES (s.SettingKey, s.SettingValue);
GO

-- Password for all seed users: ProjectHub123!
-- bcrypt hash generated by server seed script; insert via API or run server/db/seed.js

PRINT 'Settings seeded. Run: npm run seed (in server folder) to create users and sample projects.';
GO
